"""
A set of abstractions for making build scripts for competitive programs

This framework is aimed to be useful for a specific approach
to competitive programming in a specific use case.
In most cases, you should probably just use a simple batch script or a makefile.

The most trivial usage example is building a single file.

    from cp import *

    clean_folder()
    if build_file('file.cpp'):
        run_with_file('./file', './test.in')

This will first clean the work folder of any temporary files
generated by the compiler (especially PDBs on Windows),
then build the file with the best compiler it can find with common options,
then run the file with redirected input if the build was successful.

The build_file function also contains a basic incremental build system, which
just compares the source file and saves it to the .cp directory.

"""

from .cp import (
    source_filename_to_exe,
    build_file,
    run_with_file,
    sio2jail_with_file,
    sio2jail_run_tests,
    clean_folder,
)

